lib: suppress false-positive -Wanalyzer-deref-before-check
GCC analyzer from GCC 13 reports an error when a pointer dereference
followed by a memcpy:

  x509_dn.c:54:17: error: check of '*name.data' for NULL after already dereferencing it [-Werror=analyzer-deref-before-check]
     54 |                 memcpy(_oid, name->data, name->size);
        |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is a false-positive, because we check name->size is > 0 on a
previous line.

Signed-off-by: Daiki Ueno <ueno@gnu.org>