oss-fuzz: use CC rather than CXX to compile fuzzers
clang++ will choke on several fuzzer sources because C++ is stricter
than C wrt. type conversion:

gnutls_base64_decoder_fuzzer.c:26:63: error: non-constant-expression
cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'unsigned
int' in initializer list [-Wc++11-narrowing]
        gnutls_datum_t raw = {.data = (unsigned char *)data, .size = size};

Signed-off-by: Dmitry Baryshkov <dbaryshkov@gmail.com>